# ╭──────────────────────────────────────ImplementationGuide───────────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see: https://fshschool.org/sushi/configuration/                         │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: fhir.emr.lis.bt
canonical: http://openhie.github.io/covid-19
name: FhirEmrLisBT
status: draft
version: 0.2.0
fhirVersion: 4.0.1
# copyright:
copyrightYear: 2020+
releaseLabel: ci-build
title: EMR-LIS HIE Communication in Botwana
description: TODO
license: CC-BY-SA-4.0
publisher:
  name: I-TECH-UW
  url: http://www.go2itech.org
  email: pmanko@uw.edu
  contact: Piotr W Mankowski
jurisdiction: http://unstats.un.org/unsd/methods/m49/m49.htm#001
# experimental: true
 
# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To use a provided ig-data/input/includes/menu.xml file, delete the "menu" property below.     │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
# menu:
#   Home: index.html
#   Table of Contents: toc.html
#   Artifacts: artifacts.html

# resources:
#  StructureDefinition/my-us-covid-observation:
#    name: My US Covid Observation
#    description: "TODO too"    
  # StructureDefinition/oncology-AverageCEP17SignalsPerCell-model:
  #   name: oncology-AverageCEP17SignalsPerCell-model
  #   description: "TODO too"    
